services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    # Use a locally-built image name so users can build from this codebase
    image: shinmen8848/shinos:latest
    container_name: shinos
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      # Secrets should be provided via .env file or external environment
      # Example: OPENAI_API_KEY=your_key_here
      # Example: WEBUI_SECRET_KEY=your_secret_here
      - 'OPENAI_API_KEY=${OPENAI_API_KEY:-}'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
